package Font.forms;

import Font.Exceptions.InputIncorrecto;
import Font.Exceptions.NoExisteNingunProducto;
import Font.Exceptions.NoExisteProducto;
import Font.Exceptions.StringVacia;
import Font.presentation.ControladorPresentacion;
import Font.presentation.RoundButtons;

import javax.swing.*;
import javax.swing.text.html.parser.Parser;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 * Esta clase junto a su form muestra la vista secundaria que permite cambiar la similitud
 * entre dos productos particulares que recibe al ser creada.
 */
public class CambiarSimWindow {
    private JPanel panel1;
    private JLabel nombre1;
    private JLabel nombre2;
    private JTextField textField1;
    private JPanel panel_boton;
    private RoundButtons bcambios;
    String producto1;
    String producto2;

    ControladorPresentacion parent;

    public CambiarSimWindow(ArrayList<String> s, ControladorPresentacion p) {
        producto1 = s.getFirst();
        nombre1.setText(producto1);
        producto2 = s.get(1);
        nombre2.setText(producto2);
        parent = p;
        String sim = "";
        bcambios = new RoundButtons("Aplicar Cambios");
        panel_boton.add(bcambios);
        try {
            sim = p.dominioGetSimilitud(producto1, producto2).toString();
        } catch (NoExisteProducto e) {
            JOptionPane.showMessageDialog(null, "No existe el producto", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (InputIncorrecto e) {
            JOptionPane.showMessageDialog(null, "El nombre de alguno de los productos no " +
                    "cumple los criterios:\nsolo debe contener caracteres alfanuméricos, espacios, guiones bajos " +
                    "o guiones.\nEl nombre no puede contener la secuencia ----.\nEl nombre no puede terminar con un " +
                    "espacio.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NoExisteNingunProducto e) {
            JOptionPane.showMessageDialog(null, "No existe ningun producto", "Error", JOptionPane.ERROR_MESSAGE);
        }
        textField1.setText(sim);

        bcambios.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                parent.dominioCambiarSimilitud(producto1, producto2, Integer.parseInt(textField1.getText()));
                parent.actualizarVisuales();
                parent.cerrarVentanaSecundaria();
            }
        });
    }


    public JPanel getPanel() {
        return panel1;
    }

    public String getNombre() {
        return "Editar Similitud";
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setBackground(new Color(-2238276));
        panel1.setForeground(new Color(-2238276));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 4, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-2238276));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 3;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel2, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Similitud:");
        panel2.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textField1 = new JTextField();
        panel2.add(textField1, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panel2.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        panel2.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel3.setBackground(new Color(-2238276));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel3, gbc);
        nombre2 = new JLabel();
        nombre2.setText("Label");
        panel3.add(nombre2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nombre1 = new JLabel();
        nombre1.setText("Label");
        panel3.add(nombre1, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panel_boton = new JPanel();
        panel_boton.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel_boton.setBackground(new Color(-4869991));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel_boton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
