package Font.forms;

import Font.Exceptions.*;
import Font.presentation.ControladorPresentacion;
import Font.presentation.RoundButtons;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 * Esta clase junto a su form muestra la vista secundaria usada para cambiar los atributos de un producto
 * particular, el cual recibe al ser creada.
 */
public class CambiarProdWindow {

    private JPanel jpanel1;
    private JTextField nombre;
    private JPanel panelboton;
    private JTextField imagenField;
    private RoundButtons boton;
    String producto;

    ControladorPresentacion parent;

    public CambiarProdWindow(ArrayList<String> s, ControladorPresentacion p) {
        parent = p;
        producto = s.getFirst();
        nombre.setText(producto);
        imagenField.setText(parent.dominioGetImagen(producto));
        boton = new RoundButtons("Aplicar Cambios");
        panelboton.add(boton);
        boton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    if (!producto.equals(nombre.getText()))
                        parent.dominioCambiarNombreProducto(producto, nombre.getText());
                    parent.dominioSetImagen(nombre.getText(), imagenField.getText());
                } catch (NoExisteProducto s) {
                    JOptionPane.showMessageDialog(null, "No existe el Producto", "Error", JOptionPane.ERROR_MESSAGE);
                } catch (InputIncorrecto s) {
                    JOptionPane.showMessageDialog(null, "El nombre del producto solo debe" +
                            " contener caracteres alfanuméricos, espacios, guiones bajos " +
                            "o guiones.\nEl nombre no puede contener la secuencia ----.\nEl nombre no puede terminar" +
                            " con un espacio.", "Error", JOptionPane.ERROR_MESSAGE);
                } catch (YaExisteProducto s) {
                    JOptionPane.showMessageDialog(null, "Ya existe", "Error", JOptionPane.ERROR_MESSAGE);
                } catch (MismoNombre s) {
                    JOptionPane.showMessageDialog(null, "Ya existe un producto con ese nombre", "Error", JOptionPane.ERROR_MESSAGE);
                } catch (NoExisteNingunProducto s) {
                    JOptionPane.showMessageDialog(null, "No existe ningun producto", "Error", JOptionPane.ERROR_MESSAGE);
                }
                parent.actualizarVisuales();
                parent.cerrarVentanaSecundaria();
            }
        });
    }

    public JPanel getPanel() {
        return jpanel1;
    }

    public String getNombre() {
        return "Editar Producto";
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jpanel1 = new JPanel();
        jpanel1.setLayout(new BorderLayout(0, 0));
        jpanel1.setBackground(new Color(-2238276));
        panelboton = new JPanel();
        panelboton.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelboton.setBackground(new Color(-4869991));
        jpanel1.add(panelboton, BorderLayout.SOUTH);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 4, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-2238276));
        jpanel1.add(panel1, BorderLayout.CENTER);
        nombre = new JTextField();
        panel1.add(nombre, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panel1.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(3, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Nombre");
        panel1.add(label1, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        panel1.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer3 = new com.intellij.uiDesigner.core.Spacer();
        panel1.add(spacer3, new com.intellij.uiDesigner.core.GridConstraints(1, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer4 = new com.intellij.uiDesigner.core.Spacer();
        panel1.add(spacer4, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        imagenField = new JTextField();
        panel1.add(imagenField, new com.intellij.uiDesigner.core.GridConstraints(2, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Imagen");
        panel1.add(label2, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jpanel1;
    }
}
