package Font.forms;

import Font.presentation.GrafoProductos;
import Font.presentation.RoundButtons;
import Font.presentation.VentanaPrincipal;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

/**
 * Esta clase junto a su form muestra una de las posibles vistas principales, esta es el primer content
 * pane que aparece en la ventana principal, solo se usa para seleccionar como entrar a la aplicación.
 */
public class LogRegWindow {
    private JPanel panel1;
    private JPanel panel2;
    private JPanel panel3;
    private JPanel aux_panel2;
    private JPanel paneltextocentral;
    private RoundButtons reg;
    private RoundButtons log;
    VentanaPrincipal parent;

    private void cambiar_a_registro() {
        parent.actionEntrarMenuReg();
    }

    private void cambiar_a_log() {
        parent.actionEntrarMenuLogin();
    }

    public LogRegWindow(VentanaPrincipal parent) {

        //Botones custom
        this.parent = parent;
        reg = new RoundButtons("Register");
        log = new RoundButtons("Log-in");
        aux_panel2.add(reg);
        aux_panel2.add(log);

        //Añadir Imagen Carrito
        ImageIcon logoIcon = new ImageIcon("Font/presentation/image_src/carritoIcon.png");
        Image logoImage = logoIcon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH); // Redimensionar la imagen
        logoIcon = new ImageIcon(logoImage);
        JLabel logoLabel = new JLabel(logoIcon);
        panel3.add(logoLabel);

        //Añadir textos
        logoLabel = new JLabel("Market Planner");
        panel3.add(logoLabel);

        //Añadir GIF
        ImageIcon gifIcon = new ImageIcon("Font/presentation/image_src/Gif_Def.gif");
        JLabel gifLabel = new JLabel(gifIcon);
        gifLabel.setHorizontalAlignment(SwingConstants.CENTER);
        gifLabel.setVerticalAlignment(SwingConstants.CENTER);
        paneltextocentral.add(gifLabel, BorderLayout.CENTER);

        reg.addActionListener(e -> cambiar_a_registro());
        log.addActionListener(e -> cambiar_a_log());

    }

    public JPanel getPanel() {
        return panel1;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panel1.setBackground(new Color(-2238276));
        panel1.setEnabled(true);
        panel1.setForeground(new Color(-2238276));
        panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel2.setBackground(new Color(-4869991));
        panel2.setEnabled(true);
        panel1.add(panel2, BorderLayout.SOUTH);
        aux_panel2 = new JPanel();
        aux_panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        aux_panel2.setBackground(new Color(-4869991));
        panel2.add(aux_panel2);
        panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel3.setBackground(new Color(-4869991));
        panel3.setEnabled(true);
        panel1.add(panel3, BorderLayout.NORTH);
        paneltextocentral = new JPanel();
        paneltextocentral.setLayout(new BorderLayout(0, 0));
        paneltextocentral.setBackground(new Color(-2238276));
        paneltextocentral.setInheritsPopupMenu(false);
        paneltextocentral.setMaximumSize(new Dimension(3200, 3200));
        paneltextocentral.setOpaque(false);
        paneltextocentral.setPreferredSize(new Dimension(10, 10));
        panel1.add(paneltextocentral, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
